name: Imprimir valores de formulario

on:
  repository_dispatch:
    types: [formulario]

jobs:
  imprimir-valores:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir valores
        run: echo "hola"
        #run: echo "Nombre: ${{ github.event.client_payload.nombre }} Apellidos: ${{ github.event.client_payload.apellidos }} Dirección: ${{ github.event.client_payload.direccion }}"
