name: Ejemplo de Pipeline con Parámetros -> quesi.yml

on:
  workflow_dispatch:
    inputs:
      entorno:
        description: 'Selecciona un entorno'
        required: true
        default: 'ubuntu-latest'
        choices: |
          ubuntu-latest: Ubuntu 20.04 LTS
          windows-latest: Windows 2019

jobs:
  Ejecutar_en:
    runs-on: ${{ github.event.inputs.entorno }}
    steps:
      - name: Ejecutar Comando en Entorno Seleccionado
        run: echo "Ejecutando en el entorno ${{ github.event.inputs.entorno }}"